[package]
name = "okta-jwt-verifier"
version = "0.1.0"
authors = ["Christian Haynes <06chaynes@gmail.com>"]
repository = "https://gitlab.com/06chaynes/okta-jwt-verifier.git"
readme = "README.md"
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
dotenv = "0.15"
jsonwebkey = { version = "0.3", features=["jwt-convert"]}
jsonwebtoken = "7.2"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
surf = "2.2"
thiserror = "1.0"

[dev-dependencies]
async-std = { version = "1.9", features = ["attributes"]}