[package]
name = "okta-jwt-verifier"
description = "A helper library for working with JWT's for Okta in Rust"
version = "0.3.0"
authors = ["Christian Haynes <06chaynes@gmail.com>"]
repository = "https://gitlab.com/06chaynes/okta-jwt-verifier.git"
homepage = "https://gitlab.com/06chaynes/okta-jwt-verifier"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["okta", "jwt"]
categories = [
    "web-programming"
]
edition = "2018"

[dependencies]
anyhow = "1.0"
jsonwebkey = { version = "0.3", features = ["jwt-convert"]}
jsonwebtoken = "7.2"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
surf = "2.3"
surf-middleware-cache = { version = "0.2", optional = true }

[dev-dependencies]
async-trait = "0.1"
async-std = { version = "1.10", features = ["attributes"]}
dotenv = "0.15"
serde_json = "1.0"
tide = "0.16"
tide-http-auth = "0.5"
jsonwebkey = "0.3"
jsonwebtoken = "7.2"

[features]
default = []
disk-cache = ["surf-middleware-cache"]