name: rust

on:
  push:
    branches: [latest]
  pull_request:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: "rustfmt"
      - run: cargo fmt -- --check

  test:
    name: Test stable on ${{ matrix.os }}
    needs: [fmt]
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: |
          cargo test --all-targets
          cargo test --all-targets --features cache-surf
          cargo test --all-targets --no-default-features --features client-reqwest
          cargo test --all-targets --no-default-features --features client-reqwest,cache-reqwest

  clippy:
    name: Check clippy
    needs: [fmt, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: "clippy"
      - run: |
          cargo clippy --lib --tests --all-targets -- -D warnings
          cargo clippy --lib --tests --all-targets --features cache-surf -- -D warnings
          cargo clippy --lib --tests --all-targets --no-default-features --features client-reqwest -- -D warnings
          cargo clippy --lib --tests --all-targets --no-default-features --features client-reqwest,cache-reqwest -- -D warnings

  docs:
    name: Build docs
    needs: [fmt, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        env:
          RUSTFLAGS: --cfg docsrs
          RUSTDOCFLAGS: --cfg docsrs -Dwarnings
      - run: cargo doc --no-deps --document-private-items
