name: rust

on:
  push:
    branches: [latest]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_library:
    name: Test library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup rust stable
        run: rustup toolchain install stable --profile minimal --no-self-update

      - name: Setup rust nightly
        run: rustup toolchain install nightly --profile minimal --no-self-update

      - name: Initialize cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ github.ref_name }}
          shared-key: ${{ runner.os }}
          cache-directories: "~/.npm"
          cache-all-crates: true

      - name: Install libssl-dev
        run: sudo apt install -y libssl-dev

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Check clippy
        run: |
          cargo clippy --lib --tests --all-targets -- -D warnings
          cargo clippy --lib --tests --all-targets --features cache-surf -- -D warnings
          cargo clippy --lib --tests --all-targets --no-default-features --features client-reqwest -- -D warnings
          cargo clippy --lib --tests --all-targets --no-default-features --features client-reqwest,cache-reqwest -- -D warnings

      - name: Run cargo test
        run: |
          cargo test --all-targets
          cargo test --all-targets --features cache-surf
          cargo test --all-targets --no-default-features --features client-reqwest
          cargo test --all-targets --no-default-features --features client-reqwest,cache-reqwest

      - name: Build docs
        run: cargo +nightly doc --no-deps --document-private-items
        env:
          RUSTFLAGS: --cfg docsrs
          RUSTDOCFLAGS: --cfg docsrs -Dwarnings
